### ISSUE TITLE
Parameter verification failed with 8.0.4

### ISSUE THREAD

**Issue by antibarbie** [Corsinvest/cv4pve-api-powershell#11]
### What happened?

Hello I think i just found a regression,

With 8.04, simple functions like `Get-PveClusterNextid` now fails with error "**Parameter verification failed**".

```
Get-PveClusterNextid -vmid 50000
Response            :
StatusCode          : 400
ReasonPhrase        : Parameter verification failed.
IsSuccessStatusCode : False
RequestResource     : /cluster/nextid
Parameters          : {[vmid, 50000]}
Method              : Get
ResponseType        : json

```

### Expected behavior

with 8.0.3 behaviour is ok :

```
Get-PveClusterNextid -vmid 50000

Response            : @{data=50017}
StatusCode          : 200
ReasonPhrase        :
IsSuccessStatusCode : True
RequestResource     : /cluster/nextid
Parameters          : {[vmid, 50000]}
Method              : Get
ResponseType        : json
```

### Proxmox VE Version

7.4

### Version (bug)

8.0.4

### Version (working)

8.0.3

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Fix in new release
