### ISSUE TITLE
How to execute commands on VM via QEMU

### ISSUE THREAD

**Issue by HenrikPedDK** [Corsinvest/cv4pve-api-powershell#13]
### What happened?

I need to be able to execute commands on my VMs (qm guest exec). I can do this with the shell on the host directly, but it would be nice to be able to do it via Powershell as well. Do you have a way to do this through PS or would you maybe consider implementing it in your plugin?

### Expected behavior

I am filing this question here because i was told to :)

### Proxmox VE Version

8.x

### Version (bug)

8.x

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Hi,
in documentation https://raw.githack.com/Corsinvest/cv4pve-api-powershell/master/doc/index.html
searxch **New-PveNodesQemuAgentExec**.

https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/exec
https://pve.proxmox.com/wiki/Qemu-guest-agent
https://pve.proxmox.com/wiki/Windows_10_guest_best_practices

best regards

**Comment by franklupo** [comment]
News?
