### ISSUE TITLE
Windows Specific command execution

### ISSUE THREAD

**Issue by AdminSecNum** [Corsinvest/cv4pve-api-powershell#14]
### What happened?

Hello, I have a few questions.

I'm coming from VMware and was using PowerCLI to do my VM creation + configuration.

However with ( cv4pve-api-powershell | PVE-API ) I encounter some problems:

1 - I have the impression that anything related to url encoding is prohibited.
1.1 - For example if I have a password like "P@s+w0r&&rd!", I receive a failed authentication; if I use "P@ssw0rd!" No problem

How to avoid this kind of problem? (For example passwords are generated randomly and removing possible chars from url encoding is not an option)

2 - Sending a command does not allow you to send a group of commands:

```
$Cmd3 = @"
touch /home/manager/pve3
echo 'test' > /home/manager/pve3
"@

New-PveNodesQemuAgentExec -PveTicket $PveTicket `
                           -Node $Node_Name `
                           -Vmid 500 `
                           -Command $Cmd3
```

Same as for point 1, if I use &&

```
New-PveNodesQemuAgentExec -PveTicket $PveTicket `
                           -Node $Node_Name `
                           -Vmid 500 `
                           -Command "touch /home/manager/pve4 && echo 'test' > /home/manager/pve4"
```

How can I send blocks of orders?

The goal being that under Windows if the commands "follow each other" in the terminal I can use the variables sent previously such as for example:

(The tild allows me that powershell does not interpret the variable currently, but that the vm which receives it does (The tild is removed when it is received by the vm) finally it worked under PowerCli->Windows I think that will be the case here too I haven't tested)

```
`$Username = $Username
`$Password = ConvertTo-SecureString $Password -AsPlainText -Force
`$Credential = New-Object System.Management.Automation.PSCredential(`$Username, `$password)
Start-Process Executable1.exe -Credential `$Credential
```

the try with 

```
New-PveNodesQemuAgentFileWrite
```

Work for the cmd3 example but not with the Tild example

The final goal is to be able to fully configure a Windows server, for example, via this API:
- Create the VM
- Configure the vm (Host name, network, Disk, etc.)
- Add and configure the role (Active Directory for example)

Perhaps one or more elements are the "fault" of the PVE API and necessarily of the Powershell module, I'm just trying to understand how to migrate my massive scripts to this module without "too much" change.

Even if I more or less understood that the simplest would be to send the scripts 1 by 1 to the VM rather than direct execution through the API.

### Expected behavior

N/A

### Proxmox VE Version

5.15.131-3

### Version (bug)

1.0.0

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Hi,
the version of Proxmox VE you are using is no longer supported. I advise you to update it to 8. 
As regards the commands you need to read the Promoxm VE API documentation https://pve.proxmox.com/pve-docs/api-viewer/

best reagrds

**Comment by AdminSecNum** [comment]
Proxmox updated in 8.1.4, but still the same `Exception: authentication failure` with complex password with `+` in

**Comment by AdminSecNum** [comment]
Trying to pass command with argument not work 

```
New-PveNodesQemuAgentExec -PveTicket $PveTicket `
                          -Node $Node_Name `
                          -Vmid 200 `
                          -Command @('C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', '-Command', 'echo', 'test')
```
```
Response            : 
StatusCode          : 500
ReasonPhrase        : Agent error: Guest agent command failed, error was 'Failed to execute child process (Invalid argument)'
IsSuccessStatusCode : False
RequestResource     : /nodes/XXXXX/qemu/200/agent/exec
Parameters          : {[command, System.Object[]]}
Method              : Post
ResponseType        : json
```
Any advice ?

**Comment by franklupo** [comment]
> Proxmox updated in 8.1.4, but still the same `Exception: authentication failure` with complex password with `+` or `#` and `&`
> 
> Can be solved with :
> 
> ```
> $PVE_Pass = [uri]::EscapeDataString('@b3kpJFY^$HLWVM{TpVL#+&')
> ```

now add support encription password

**Comment by franklupo** [comment]
Fix in new version
