### ISSUE TITLE
Enter-PveSPice not found

### ISSUE THREAD

**Issue by duke8804** [Corsinvest/cv4pve-api-powershell#16]
### What happened?

installed and imported the module. Everything else seems to work, just not Enter-PveSpice

Show-PveSpice: The term 'Enter-PveSpice' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Expected behavior

Enter-PveSpice is found

### Relevant log output

```shell
Show-PveSpice: The term 'Enter-PveSpice' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Proxmox VE Version

8.2.2

### Version (bug)

8.2.0

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Use Invoke-PveSpice. I fix the documentation.

Best regards
