### ISSUE TITLE
Upid

### ISSUE THREAD

**Issue by blendiTahiri** [Corsinvest/cv4pve-api-powershell#4]
### What happened?

Iam using the -upid Parameter which exists in the variable delete. But when i use it I get the the error Code that it cannot be found.
![image](https://user-images.githubusercontent.com/40654490/156730213-2661e83d-b267-4450-b935-c2b448e2bafd.png)

### Expected behavior

In the delete.Response the upid is available. But when i wanna call it with Wait-PveTaskIsFinish -Upid $deltete.Response.data, I get the error Code Get-PveNodesTasks: A parameter cannot be found that matches parameter name 'Upid'.
![image](https://user-images.githubusercontent.com/40654490/156730465-a0a27c1d-97f0-4555-aa65-469e33932fa0.png)

### Proxmox VE Version

7.1

### Version (bug)

7.2

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [X] I would like to do a Pull Request

**Comment by franklupo** [comment]
Fixed in the new version 7.1.2
Please check if it works.

best regards

**Comment by blendiTahiri** [comment]
Hi
It works now :) Thank you very much

Kind regards
