### ISSUE TITLE
Syntax requirement

### ISSUE THREAD

**Issue by videlicetIHOPE** [Corsinvest/cv4pve-api-powershell#5]
hello,
Unable to write a satisfying request in powershell, equivalent to a pvesh command

====================

For an api request with pvesh 
pvesh set /nodes/precision/qemu/105/config -ipconfig0 "ip=10.1.1.21/24,gw=10.1.1.254"

Result
update VM 105: -ipconfig0 ip=10.1.1.21/24,gw=10.1.1.254

================

But with powershell

==================
$ipval=@{}
$ipval[0]="ip=10.1.1.21/24,gw=10.1.1.254"
PS C:\Users\user\Desktop> set-PveNodesQemuConfig  -vmid 105 -Node proxserver  -IpconfigN $ipval

StatusCode          : 400
IsSuccessStatusCode : False
Response            : 
ReasonPhrase        : Parameter verification failed.
RequestResource     : /nodes/proxserver/qemu/105/config
Parameters          : {ipconfig0}
Method              : Put
ResponseType        : json

========================

Sorry if i made a basic error with PS, I am not very familiar.

perhaps add an example with Hashtables to the doc.
thank you,
Best regards,
ken

**Comment by franklupo** [comment]
Hi,
check the problem.

Best regards

**Comment by franklupo** [comment]
Found the problem. I prepare the fix and release the new version.

Best regards
