### ISSUE TITLE
Get-PveVm with -PveTicket parameter

### ISSUE THREAD

**Issue by AlxVD** [Corsinvest/cv4pve-api-powershell#6]
### What happened?

Parameter is not accepted with error:
[Get-PveVm: Cannot process argument transformation on parameter 'PveTicket'. Cannot convert the "PveTicket" value of type "PveTicket" to type "System.Management.Automation.ValidateNotNullAttribute".]

![bug](https://github.com/Corsinvest/cv4pve-api-powershell/assets/15388258/120f0b98-276c-4fc1-845c-19cfa45debd5)

### Expected behavior

Commandlet executes successfully

### Proxmox VE Version

7.4.3

### Version (bug)

8.0

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Hi,
update new version.
if you don't specify the -PveTicket parameter, the library uses the last one created which is saved in the global variable $PveTicketLast.

best regards
