### ISSUE TITLE
Obscure error message at Copy-PveQemu

### ISSUE THREAD

**Issue by AlxVD** [Corsinvest/cv4pve-api-powershell#7]
### What happened?

Running this command
![image](https://github.com/Corsinvest/cv4pve-api-powershell/assets/15388258/e965c525-2b46-4e87-9506-7201ca8a78f1)

### Expected behavior

Expected a successful result

### Proxmox VE Version

7.4.16

### Version (bug)

8.0.2

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by AlxVD** [comment]
Btw - this error message has wrong '\n' inside.

**Comment by franklupo** [comment]
New version was released.

best regards
