### ISSUE TITLE
Start-PveVm is broken

### ISSUE THREAD

**Issue by AlxVD** [Corsinvest/cv4pve-api-powershell#8]
### What happened?

![image](https://github.com/Corsinvest/cv4pve-api-powershell/assets/15388258/15387591-3c1d-474b-a26d-002e94898bd1)

### Expected behavior

VM started

### Proxmox VE Version

7.4.17

### Version (bug)

8.0.3

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

**Comment by franklupo** [comment]
Use version 7 of library

**Comment by franklupo** [comment]
8.0.4 published
